#!/usr/bin/env python3
"""Expand generated v3 candidate samples from legacy coarse tasks to finer annotation tasks.

Default mapping:
  pick_up    -> lift
  lift_carry -> lift
  open_pull  -> open, pull
  press_push -> press, push

This script is intended for *post-pipeline, pre-human-annotation* JSONL files,
for example v3_candidate_samples_v0_1.jsonl generated by run_v3_pipeline.py.
It does not regenerate candidates. It reuses existing candidate/mask/point-cloud
paths and creates duplicated annotation rows with task provenance fields.

Important:
  - Do not feed the new-task JSONL back into scripts that still validate tasks
    only against legacy tasks unless those scripts are updated.
  - Use the output as annotation input or reviewer package input.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils.task_taxonomy import (  # noqa: E402
    LEGACY_TO_NEW_TASKS,
    TASK_TAXONOMY_VERSION,
    is_new_task,
    task_display,
    task_instruction,
)

DEFAULT_TASK_MAP: dict[str, list[str]] = dict(LEGACY_TO_NEW_TASKS)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split generated v3 candidate samples into lift/open/pull/press/push annotation tasks."
    )
    parser.add_argument("--input", required=True, help="Input v3_candidate_samples JSONL path.")
    parser.add_argument("--output", required=True, help="Output expanded JSONL path. Refuses to overwrite unless --overwrite.")
    parser.add_argument("--summary-json", default="", help="Optional summary JSON path.")
    parser.add_argument(
        "--task-field-mode",
        choices=["replace", "alias_only"],
        default="replace",
        help=(
            "replace: set row['task'] to lift/open/pull/press/push. "
            "alias_only: keep legacy row['task'] and write row['target_task'] instead. "
            "Use alias_only only if your annotation app rejects unknown task names."
        ),
    )
    parser.add_argument(
        "--unknown-policy",
        choices=["keep", "skip", "error"],
        default="keep",
        help="What to do with rows whose task is not a known legacy or five-task task.",
    )
    parser.add_argument(
        "--id-style",
        choices=["replace_suffix", "append"],
        default="replace_suffix",
        help="How to create new sample_id/task_instance_id values.",
    )
    parser.add_argument(
        "--keep-pilot-id",
        action="store_true",
        default=True,
        help="Keep original pilot_id so existing candidate directories remain reusable. This is the default.",
    )
    parser.add_argument(
        "--set-review-id",
        action="store_true",
        default=True,
        help="Set/overwrite review_id with a unique id for the expanded row. This is the default.",
    )
    parser.add_argument(
        "--no-set-review-id",
        dest="set_review_id",
        action="store_false",
        help="Do not set/overwrite review_id.",
    )
    parser.add_argument("--overwrite", action="store_true", help="Allow overwriting output files.")
    return parser.parse_args()


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8-sig") as f:
        for line_no, line in enumerate(f, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                obj = json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{line_no}: {exc}") from exc
            if not isinstance(obj, dict):
                raise ValueError(f"Each JSONL row must be an object at {path}:{line_no}")
            obj.setdefault("_source_line_no", line_no)
            rows.append(obj)
    return rows


def write_jsonl(path: Path, rows: list[dict[str, Any]], overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists. Use --overwrite to replace it: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        for row in rows:
            row = dict(row)
            row.pop("_source_line_no", None)
            f.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")))
            f.write("\n")


def write_json(path: Path, data: dict[str, Any], overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Summary exists. Use --overwrite to replace it: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")


def sanitize_id(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value).strip())
    value = re.sub(r"_+", "_", value)
    return value.strip("_")


def replace_task_token(value: str, old_task: str, new_task: str, id_style: str) -> str:
    value = str(value or "").strip()
    if not value:
        return value
    if id_style == "append":
        return sanitize_id(f"{value}__task_{new_task}")

    # Prefer replacing task suffixes because sample_id is usually objectid_task.
    suffixes = [f"_{old_task}", f"-{old_task}", f".{old_task}"]
    for suffix in suffixes:
        if value.endswith(suffix):
            return sanitize_id(value[: -len(suffix)] + suffix.replace(old_task, new_task))

    # Also handle embedded task token bounded by separators.
    pattern = re.compile(rf"(?<![A-Za-z0-9]){re.escape(old_task)}(?![A-Za-z0-9])")
    replaced = pattern.sub(new_task, value)
    if replaced != value:
        return sanitize_id(replaced)

    return sanitize_id(f"{value}__task_{new_task}")


def get_executor(row: dict[str, Any]) -> str:
    return str(row.get("target_executor") or row.get("executor") or "unknown")


def make_unique(base: str, seen: set[str]) -> str:
    base = sanitize_id(base) or "sample"
    if base not in seen:
        seen.add(base)
        return base
    index = 2
    while True:
        candidate = f"{base}__dup{index}"
        if candidate not in seen:
            seen.add(candidate)
            return candidate
        index += 1


def expand_row(
    row: dict[str, Any],
    old_task: str,
    new_task: str,
    args: argparse.Namespace,
    seen_sample_ids: set[str],
    seen_review_ids: set[str],
) -> dict[str, Any]:
    out = copy.deepcopy(row)

    original_sample_id = str(row.get("sample_id") or "")
    original_pilot_id = str(row.get("pilot_id") or "")
    original_review_id = str(row.get("review_id") or "")
    executor = get_executor(row)

    new_sample_id_base = replace_task_token(original_sample_id, old_task, new_task, args.id_style)
    if not new_sample_id_base:
        object_id = str(row.get("object_id") or "object")
        new_sample_id_base = sanitize_id(f"{object_id}_{new_task}_{executor}")
    new_sample_id = make_unique(new_sample_id_base, seen_sample_ids)

    if args.task_field_mode == "replace":
        out["task"] = new_task
        out["legacy_task"] = old_task
    else:
        out["task"] = old_task
        out["target_task"] = new_task

    out["sample_id"] = new_sample_id
    out["task_display"] = task_display(new_task)
    out["task_instruction"] = task_instruction(new_task)
    out["task_taxonomy_version"] = TASK_TAXONOMY_VERSION
    out["task_split_source"] = "legacy_task_expansion"
    out["source_task"] = old_task
    out["source_sample_id"] = original_sample_id
    if original_pilot_id:
        out["source_pilot_id"] = original_pilot_id
        out["candidate_pilot_id"] = original_pilot_id
        # Keep pilot_id unchanged so existing 3d_candidates/<pilot_id>/candidate_manifest.json can be reused.
        out["pilot_id"] = original_pilot_id
    if original_review_id:
        out["source_review_id"] = original_review_id

    task_instance_base = f"{new_sample_id}_{executor}"
    out["task_instance_id"] = sanitize_id(task_instance_base)
    if args.set_review_id:
        out["review_id"] = make_unique(task_instance_base, seen_review_ids)
    out["row_key"] = "|".join(
        [
            str(out.get("review_id") or out.get("pilot_id") or ""),
            new_sample_id,
            new_task,
            executor,
        ]
    )

    # Keep original paths unchanged: point clouds, masks and candidate manifests are reused as proposals.
    out["task_split_note"] = (
        "This row was expanded from a legacy coarse task after candidate generation. "
        "Existing candidate/mask paths are reused only as annotation proposals; "
        "human review must decide the final mask under the new task definition."
    )
    out["quality_flag"] = "weak" if str(out.get("quality_flag") or "") in {"", "weak", "checked", "verified"} else out.get("quality_flag")
    out["needs_human_review"] = True

    # Do not leave stale user-facing reason text that says open_pull/press_push if it exists.
    if "pilot_reason" in out:
        out["pilot_reason"] = (
            str(out.get("pilot_reason") or "")
            + f" Task was split from {old_task} to {new_task}; reviewer should judge under the new task semantics."
        ).strip()

    return out


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    if not input_path.exists():
        raise FileNotFoundError(f"Input JSONL does not exist: {input_path}")

    rows = read_jsonl(input_path)
    expanded: list[dict[str, Any]] = []
    skipped = Counter()
    counts_by_source_task = Counter()
    counts_by_new_task = Counter()
    counts_by_executor = Counter()
    counts_by_category = Counter()
    seen_sample_ids: set[str] = set()
    seen_review_ids: set[str] = set()

    for row in rows:
        old_task = str(row.get("task") or "")
        new_tasks = DEFAULT_TASK_MAP.get(old_task)
        if not new_tasks and is_new_task(old_task):
            kept = copy.deepcopy(row)
            original_sid = str(kept.get("sample_id") or f"task_{len(expanded)+1}")
            sid = original_sid
            kept["sample_id"] = make_unique(sid, seen_sample_ids)
            if args.set_review_id:
                rid = str(kept.get("review_id") or f"{kept['sample_id']}_{get_executor(kept)}")
                kept["review_id"] = make_unique(rid, seen_review_ids)
            kept["task_taxonomy_version"] = TASK_TAXONOMY_VERSION
            kept.setdefault("task_display", task_display(old_task))
            kept.setdefault("task_instruction", task_instruction(old_task))
            kept.setdefault("task_split_source", "already_five_task")
            kept.setdefault("source_task", old_task)
            kept.setdefault("source_sample_id", original_sid)
            kept.setdefault(
                "row_key",
                "|".join(
                    [
                        str(kept.get("review_id") or kept.get("pilot_id") or ""),
                        str(kept.get("sample_id") or ""),
                        old_task,
                        get_executor(kept),
                    ]
                ),
            )
            expanded.append(kept)
            counts_by_new_task[old_task] += 1
            counts_by_executor[get_executor(kept)] += 1
            counts_by_category[str(kept.get("object_category") or "unknown")] += 1
            continue
        if not new_tasks:
            if args.unknown_policy == "error":
                raise ValueError(
                    f"Unknown task {old_task!r} at input line {row.get('_source_line_no')}. "
                    f"Known legacy tasks: {sorted(DEFAULT_TASK_MAP)}"
                )
            if args.unknown_policy == "skip":
                skipped[f"unknown_task_skipped:{old_task}"] += 1
                continue
            # keep unknown row unchanged, but ensure sample_id uniqueness.
            kept = copy.deepcopy(row)
            original_sid = str(kept.get("sample_id") or f"unknown_{len(expanded)+1}")
            sid = original_sid
            kept["sample_id"] = make_unique(sid, seen_sample_ids)
            if args.set_review_id:
                rid = str(kept.get("review_id") or f"{kept['sample_id']}_{get_executor(kept)}")
                kept["review_id"] = make_unique(rid, seen_review_ids)
            kept["task_taxonomy_version"] = TASK_TAXONOMY_VERSION
            kept.setdefault("task_display", task_display(old_task))
            kept.setdefault("task_instruction", task_instruction(old_task))
            kept.setdefault("task_split_source", "kept_unknown_or_already_new")
            kept.setdefault("source_task", old_task)
            kept.setdefault("source_sample_id", original_sid)
            kept.setdefault(
                "row_key",
                "|".join(
                    [
                        str(kept.get("review_id") or kept.get("pilot_id") or ""),
                        str(kept.get("sample_id") or ""),
                        str(kept.get("task") or kept.get("target_task") or ""),
                        get_executor(kept),
                    ]
                ),
            )
            expanded.append(kept)
            skipped[f"unknown_task_kept:{old_task}"] += 1
            continue

        for new_task in new_tasks:
            out = expand_row(row, old_task, new_task, args, seen_sample_ids, seen_review_ids)
            expanded.append(out)
            counts_by_source_task[old_task] += 1
            counts_by_new_task[new_task] += 1
            counts_by_executor[get_executor(out)] += 1
            counts_by_category[str(out.get("object_category") or "unknown")] += 1

    write_jsonl(output_path, expanded, args.overwrite)

    summary = {
        "input": str(input_path),
        "output": str(output_path),
        "task_taxonomy_version": TASK_TAXONOMY_VERSION,
        "task_field_mode": args.task_field_mode,
        "rows_input": len(rows),
        "rows_output": len(expanded),
        "mapping": DEFAULT_TASK_MAP,
        "counts_by_source_task_after_expansion": dict(sorted(counts_by_source_task.items())),
        "counts_by_new_task": dict(sorted(counts_by_new_task.items())),
        "counts_by_executor": dict(sorted(counts_by_executor.items())),
        "counts_by_category": dict(sorted(counts_by_category.items())),
        "skipped": dict(sorted(skipped.items())),
        "notes": [
            "Candidate paths are reused; this script does not regenerate point clouds, masks, or 3D candidates.",
            "Use this output for human annotation/reviewer packaging, not as final ground truth.",
            "If downstream scripts reject lift/open/pull/press/push, rerun with --task-field-mode alias_only or update task validators.",
        ],
    }
    if args.summary_json:
        write_json(Path(args.summary_json), summary, args.overwrite)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
